"""empty message

Revision ID: a74677003727
Revises: 90d38a83fd23
Create Date: 2026-02-11 11:25:45.028014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74677003727'
down_revision = '90d38a83fd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito_lugar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lugar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje_simpson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorito_simpson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito_simpson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lugar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], name='favorito_simpson_lugar_id_fkey'),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje_simpson.id'], name='favorito_simpson_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_simpson_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_simpson_pkey')
    )
    op.drop_table('favorito_personaje')
    op.drop_table('favorito_lugar')
    # ### end Alembic commands ###
